@host = http://localhost:5008
@hostId = 00000000-0000-0000-0000-000000000000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1Y2U5ZDk5OC0zMjNkLTQ0NmMtYWU3MS05NGU3OWI5MzFhZjUiLCJnaXZlbl9uYW1lIjoiRW1tYSIsImZhbWlseV9uYW1lIjoiV2F0c29uIiwianRpIjoiMDE3NTdmOTgtMzdhYS00NGYxLTkwNGQtN2RmMGNhMzFjNDA3IiwiZXhwIjoxNjk2NTEyMjAzLCJpc3MiOiJEZWxpZ2h0RGlubmVyIiwiYXVkIjoiRGVsaWdodERpbm5lciJ9.7venjSA-S6HFgNAcFw8QMAiz_00v0pS8HLnsdr2cUOw

POST {{host}}/hosts/{{hostId}}/menus
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Yummy Menu",
    "description": "A menu with yummy food",
    "sections": [
        {
            "name": "Appetizers",
            "description": "Starters",
            "items": [
                {
                    "name": "Fried Pickles",
                    "description": "Deep fried pickles"
                }
            ]
        }
    ]
}