@host = http://localhost:5008
@hostId = 00000000-0000-0000-0000-000000000000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiYTFmYjZhOC05YTI2LTRhNDAtYjQyZC00ZTU5ZTQ5MzhkYzAiLCJnaXZlbl9uYW1lIjoiRW1tYSIsImZhbWlseV9uYW1lIjoiV2F0c29uIiwianRpIjoiOTBiZjljNjctNmIxMS00YzRhLWJiNDItZWI2MWFiY2VkYjNiIiwiZXhwIjoxNjk2NDI3Njg1LCJpc3MiOiJEZWxpZ2h0RGlubmVyIiwiYXVkIjoiRGVsaWdodERpbm5lciJ9.es56UeeDzpcv-N2irzyFUPVIsn41DC4E2b-YOkpw0UU

GET {{host}}/hosts/{{hostId}}/menus
Authorization: Bearer {{token}}